# Generated by Django 4.2.4 on 2023-08-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                default="default_username", max_length=50, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
