# Generated by Django 4.2.4 on 2023-08-12 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("videoname", models.CharField(max_length=255)),
                ("videouploaddate", models.DateTimeField(auto_now_add=True)),
                (
                    "user_upload",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_detail",
                        to="feedback.userupload",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("speed", models.IntegerField()),
                ("accuracy", models.DecimalField(decimal_places=2, max_digits=5)),
                ("intensity", models.IntegerField()),
                ("posture", models.CharField(max_length=255)),
                (
                    "Video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="feedback.video",
                    ),
                ),
            ],
        ),
    ]
