# Generated by Django 4.2.4 on 2023-08-15 06:02

from django.db import migrations, models
import feedback.models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0002_video_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userupload",
            name="video",
            field=models.FileField(upload_to=feedback.models.name_path),
        ),
    ]
