# Generated by Django 4.2.4 on 2023-08-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0003_alter_userupload_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="userupload",
            name="script",
            field=models.TextField(blank=True, null=True),
        ),
    ]
